# Generated by Django 4.2.13 on 2025-01-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_intrestconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('reponse', models.TextField()),
                ('max_presence_Superieur', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
