# Generated by Django 4.2.13 on 2025-01-19 15:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reponsetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponsetemplate',
            name='reponse',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
