# Generated by Django 4.2.13 on 2025-02-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_reponsetemplate_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponsetemplate',
            name='default_response',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
